//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStreamingDownloader.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoStreamingDownloader.Resources.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add to downloads.
        /// </summary>
        internal static string AddToDownloads {
            get {
                return ResourceManager.GetString("AddToDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio description.
        /// </summary>
        internal static string ads {
            get {
                return ResourceManager.GetString("ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio:.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalan.
        /// </summary>
        internal static string cat {
            get {
                return ResourceManager.GetString("cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decripting.
        /// </summary>
        internal static string Decripting {
            get {
                return ResourceManager.GetString("Decripting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloads Viewer.
        /// </summary>
        internal static string DownloadViewer {
            get {
                return ResourceManager.GetString("DownloadViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basque.
        /// </summary>
        internal static string eus {
            get {
                return ResourceManager.GetString("eus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a French.
        /// </summary>
        internal static string fra {
            get {
                return ResourceManager.GetString("fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting key.
        /// </summary>
        internal static string Getting_key {
            get {
                return ResourceManager.GetString("Getting_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting media.
        /// </summary>
        internal static string Getting_media {
            get {
                return ResourceManager.GetString("Getting_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Galician.
        /// </summary>
        internal static string glg {
            get {
                return ResourceManager.GetString("glg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link Here.
        /// </summary>
        internal static string LinkHere {
            get {
                return ResourceManager.GetString("LinkHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Merging files.
        /// </summary>
        internal static string Merging_files {
            get {
                return ResourceManager.GetString("Merging_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must choose an audio option.
        /// </summary>
        internal static string MustChooseAudio {
            get {
                return ResourceManager.GetString("MustChooseAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must choose a video option.
        /// </summary>
        internal static string MustChooseVideo {
            get {
                return ResourceManager.GetString("MustChooseVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Original version.
        /// </summary>
        internal static string qaa {
            get {
                return ResourceManager.GetString("qaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save and close.
        /// </summary>
        internal static string SaveClose {
            get {
                return ResourceManager.GetString("SaveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select all.
        /// </summary>
        internal static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select files.
        /// </summary>
        internal static string Select_files {
            get {
                return ResourceManager.GetString("Select_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        internal static string spa {
            get {
                return ResourceManager.GetString("spa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtitles:.
        /// </summary>
        internal static string Subtitles {
            get {
                return ResourceManager.GetString("Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undefined ({0}).
        /// </summary>
        internal static string UndefinedLanguageCode {
            get {
                return ResourceManager.GetString("UndefinedLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video:.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
